# Generated by Django 4.2.16 on 2026-02-20 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal_club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersofttrait',
            name='score',
            field=models.PositiveSmallIntegerField(default=5, help_text='بازه ۱ تا ۱۰', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='امتیاز'),
        ),
    ]
