# Generated by Django 4.2.16 on 2026-02-22 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal_club', '0002_alter_playersofttrait_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('insurance_expiry', 'انقضای بیمه'), ('invoice_due', 'سررسید فاکتور'), ('salary_ready', 'آماده بودن حقوق'), ('player_change', 'تغییر اطلاعات بازیکن'), ('general', 'عمومی')], default='general', max_length=30, verbose_name='نوع اعلان'),
        ),
        migrations.CreateModel(
            name='PlayerChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('profile', 'ویرایش اطلاعات شخصی'), ('insurance', 'بروزرسانی بیمه'), ('tech', 'ویرایش پروفایل فنی'), ('soft_traits', 'ویرایش ویژگی نرم'), ('archive', 'بایگانی'), ('restore', 'بازگردانی')], max_length=20, verbose_name='نوع تغییر')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_changes', to=settings.AUTH_USER_MODEL, verbose_name='توسط')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='futsal_club.player', verbose_name='بازیکن')),
            ],
            options={
                'verbose_name': 'تغییر بازیکن',
                'verbose_name_plural': 'تغییرات بازیکنان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('insurance_updated', 'بروزرسانی بیمه'), ('profile_updated', 'ویرایش اطلاعات'), ('tech_updated', 'ویرایش پروفایل فنی'), ('traits_updated', 'ویرایش ویژگی\u200cهای نرم'), ('category_changed', 'تغییر دسته'), ('archived', 'بایگانی'), ('restored', 'بازگردانی'), ('approved', 'تأیید ثبت\u200cنام')], max_length=30, verbose_name='نوع عملیات')),
                ('detail', models.CharField(blank=True, max_length=500, verbose_name='جزئیات')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_actions', to=settings.AUTH_USER_MODEL, verbose_name='انجام\u200cدهنده')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='futsal_club.player', verbose_name='بازیکن')),
            ],
            options={
                'verbose_name': 'لاگ فعالیت بازیکن',
                'verbose_name_plural': 'لاگ\u200cهای فعالیت بازیکنان',
                'ordering': ['-created_at'],
            },
        ),
    ]
