# Generated by Django 4.2.16 on 2026-02-24 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal_club', '0003_alter_notification_type_playerchangelog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('insurance_expiry', 'انقضای بیمه'), ('invoice_due', 'سررسید فاکتور'), ('invoice_issued', 'صدور فاکتور شهریه'), ('invoice_paid', 'تأیید پرداخت شهریه'), ('salary_ready', 'آماده بودن حقوق'), ('salary_paid', 'پرداخت حقوق مربی'), ('staff_invoice', 'فاکتور دستی'), ('player_change', 'تغییر اطلاعات بازیکن'), ('general', 'عمومی')], default='general', max_length=30, verbose_name='نوع اعلان'),
        ),
        migrations.CreateModel(
            name='StaffInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان فاکتور')),
                ('description', models.TextField(blank=True, verbose_name='شرح')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='مبلغ (ریال)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('canceled', 'لغو شده')], default='pending', max_length=15, verbose_name='وضعیت')),
                ('zarinpal_ref_id', models.CharField(blank=True, max_length=100, verbose_name='شماره مرجع')),
                ('zarinpal_authority', models.CharField(blank=True, max_length=100, verbose_name='Authority')),
                ('paid_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ صدور')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_staff_invoices', to=settings.AUTH_USER_MODEL, verbose_name='صادرکننده')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_invoices', to=settings.AUTH_USER_MODEL, verbose_name='دریافت\u200cکننده')),
            ],
            options={
                'verbose_name': 'فاکتور دستی',
                'verbose_name_plural': 'فاکتورهای دستی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('invoice_issued', 'صدور فاکتور شهریه'), ('invoice_paid', 'پرداخت شهریه'), ('salary_calculated', 'محاسبه حقوق'), ('salary_paid', 'پرداخت حقوق'), ('staff_invoice', 'فاکتور دستی'), ('staff_invoice_paid', 'پرداخت فاکتور دستی'), ('expense', 'ثبت هزینه'), ('income', 'ثبت درآمد')], max_length=30, verbose_name='نوع')),
                ('direction', models.CharField(choices=[('credit', 'بستانکار'), ('debit', 'بدهکار')], max_length=10, verbose_name='جهت')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='مبلغ (ریال)')),
                ('description', models.CharField(max_length=500, verbose_name='شرح')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('coach_salary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='futsal_club.coachsalary', verbose_name='حقوق مربی')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_transactions', to=settings.AUTH_USER_MODEL, verbose_name='انجام\u200cدهنده')),
                ('player_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='futsal_club.playerinvoice', verbose_name='فاکتور شهریه')),
                ('staff_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='futsal_club.staffinvoice', verbose_name='فاکتور دستی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_history', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش مالی',
                'verbose_name_plural': 'تراکنش\u200cهای مالی',
                'ordering': ['-created_at'],
            },
        ),
    ]
