# Generated by Django 4.2.16 on 2026-02-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal_club', '0004_alter_notification_type_staffinvoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachsalary',
            name='bank_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='salary_receipts/%Y/%m/', verbose_name='تصویر فیش بانکی'),
        ),
        migrations.AddField(
            model_name='staffinvoice',
            name='bank_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='staff_receipts/%Y/%m/', verbose_name='تصویر فیش بانکی'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('insurance_expiry', 'انقضای بیمه'), ('invoice_due', 'سررسید فاکتور'), ('invoice_issued', 'صدور فاکتور شهریه'), ('invoice_paid', 'تأیید پرداخت شهریه'), ('salary_ready', 'آماده بودن حقوق'), ('salary_paid', 'پرداخت حقوق مربی'), ('staff_invoice', 'فاکتور دستی'), ('payment_reminder', 'یادآوری پرداخت شهریه'), ('receipt_uploaded', 'رسید پرداخت آپلود شد'), ('player_change', 'تغییر اطلاعات بازیکن'), ('general', 'عمومی')], default='general', max_length=30, verbose_name='نوع اعلان'),
        ),
    ]
