# Generated by Django 4.2.16 on 2026-02-25 18:36

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal_club', '0005_coachsalary_bank_receipt_staffinvoice_bank_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachsalary',
            name='coach_confirmed',
            field=models.BooleanField(default=False, verbose_name='تأیید مربی'),
        ),
        migrations.AddField(
            model_name='coachsalary',
            name='coach_confirmed_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید مربی'),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='expense_receipts/%Y/%m/', verbose_name='تصویر رسید'),
        ),
        migrations.AddField(
            model_name='staffinvoice',
            name='recipient_confirmed',
            field=models.BooleanField(default=False, verbose_name='تأیید گیرنده'),
        ),
        migrations.AddField(
            model_name='staffinvoice',
            name='recipient_confirmed_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید گیرنده'),
        ),
        migrations.AlterField(
            model_name='coachsalary',
            name='status',
            field=models.CharField(choices=[('calculated', 'محاسبه شده'), ('approved', 'تأیید شده'), ('paid', 'پرداخت شده — منتظر تأیید مربی'), ('confirmed', 'تأیید دریافت توسط مربی')], default='calculated', max_length=15, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='staffinvoice',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده — منتظر تأیید گیرنده'), ('confirmed', 'تأیید دریافت توسط گیرنده'), ('canceled', 'لغو شده')], default='pending', max_length=15, verbose_name='وضعیت'),
        ),
    ]
